const healthOptions = [
	'alcohol-free',
	'immuno-supportive',
	'celery-free',
	'crustacean-free',
	'dairy-free',
	'egg-free',
	'fish-free',
	'fodmap-free',
	'gluten-free',
	'keto-friendly',
	'kidney-friendly',
	'kosher',
	'low-potassium',
	'lupine-free',
	'mustard-free',
	'low-fat-abs',
	'No-oil-added',
	'low-sugar',
	'paleo',
	'peanut-free',
	'pecatarian',
	'pork-free',
	'red-meat-free',
	'sesame-free',
	'shellfish-free',
	'soy-free',
	'sugar-conscious',
	'tree-nut-free',
	'vegan',
	'vegetarian',
	'wheat-free',
];

export default healthOptions;
